name: pytest

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
      - develop

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pytest
        with:
          python-version: ${{ matrix.python-version }}

  test_examples:
    needs: [pytest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test_examples

  linting:
    needs: [pytest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/linting

  build_docs:
    needs: [pytest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build_docs

  setup_and_build:
    needs: [test_examples, linting, build_docs]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup_and_build
        with:
          upload: true